pipeline{
    agent{
        docker{
            image 'maven:3.8.1-adoptopenjdk-11'
        }
    }
    stages{
        stage('compile'){
            steps{
                sh 'javac Hello.java'
            }
        }
        stage('Run'){
            steps{
                sh 'java Hello'
            }
        }
    }
}
